export const INITIAL_COMPANY_DETAIL_SYMBOLS = [
  "AAPL",
  "MSFT",
  "NVDA",
  "GOOGL",
  "AMZN",
  "META",
  "TSLA",
  "MELI",
  "YPF",
  "SPCX",
] as const;

export type CuratedCompanyProfile = {
  companyName: string;
  sector: string;
  industry: string;
  country: string;
  exchange: string | null;
  currency: string;
  description: string;
  businessSummary: string;
  investorFocus: string;
  keyRisks: string;
  mainSegments: string[];
  keyDrivers: string[];
  riskSensitivities: string[];
  whyInvestorsTrack: string;
  metricsFocus: string[];
  sourceType: "curated_static";
  updatedAt: string;
};

const CURATED_UPDATED_AT = "2026-06-20";

export const CURATED_COMPANY_PROFILES: Record<string, CuratedCompanyProfile> = {
  AAPL: {
    companyName: "Apple Inc.",
    sector: "Tecnologia",
    industry: "Consumer electronics / platforms",
    country: "Estados Unidos",
    exchange: "NASDAQ",
    currency: "USD",
    description: "Apple disena, fabrica y vende dispositivos personales premium y servicios digitales integrados alrededor de un ecosistema propio de hardware, software, distribucion y pagos.",
    businessSummary: "El caso de inversion combina ciclos de hardware, retencion de una base instalada global y monetizacion recurrente de servicios. La lectura correcta separa crecimiento de unidades, mezcla de servicios, margen bruto y retorno de capital.",
    investorFocus: "El mercado sigue el ciclo de iPhone, expansion de Services, monetizacion de la base instalada, disciplina de margen, recompras y exposicion a China.",
    keyRisks: "Dependencia de iPhone, regulacion de App Store, sensibilidad al consumo premium, presion competitiva y concentracion operativa en la cadena de suministro asiatica.",
    mainSegments: ["iPhone", "Mac", "iPad", "Wearables/Home/Accessories", "Services"],
    keyDrivers: ["Base instalada activa", "Mix de Services", "Ciclo de renovacion de iPhone", "Margen bruto", "Recompras"],
    riskSensitivities: ["Regulacion de plataformas", "Demanda en China", "Tipo de cambio", "Cadena de suministro", "Ciclo de consumo"],
    whyInvestorsTrack: "Es un benchmark de calidad, pricing power y retorno al accionista dentro de mega-cap tecnologia.",
    metricsFocus: ["Services growth", "Gross margin", "iPhone revenue", "Free cash flow", "Buybacks"],
    sourceType: "curated_static",
    updatedAt: CURATED_UPDATED_AT,
  },
  MSFT: {
    companyName: "Microsoft Corporation",
    sector: "Tecnologia",
    industry: "Software / cloud infrastructure",
    country: "Estados Unidos",
    exchange: "NASDAQ",
    currency: "USD",
    description: "Microsoft provee software empresarial, productividad, infraestructura cloud, seguridad, sistemas operativos, gaming y plataformas de datos e inteligencia artificial.",
    businessSummary: "La tesis se apoya en contratos enterprise recurrentes, Azure como plataforma cloud, Microsoft 365, GitHub, seguridad y monetizacion progresiva de IA en flujos de trabajo corporativos.",
    investorFocus: "El seguimiento se concentra en Azure, adopcion de Copilot/IA, margen cloud, renovaciones enterprise, capex de infraestructura y crecimiento de productividad.",
    keyRisks: "Competencia cloud, gasto intensivo en data centers, escrutinio antitrust, ejecucion en IA y sensibilidad a presupuestos corporativos.",
    mainSegments: ["Productivity and Business Processes", "Intelligent Cloud", "More Personal Computing", "Gaming"],
    keyDrivers: ["Azure growth", "Microsoft 365 ARPU", "AI attach rates", "Operating leverage", "Enterprise renewals"],
    riskSensitivities: ["Cloud pricing", "AI infrastructure capex", "Regulacion antitrust", "Ciclo de IT enterprise", "Competencia en productividad"],
    whyInvestorsTrack: "Es una de las plataformas enterprise mas diversificadas y una referencia para monetizacion de IA corporativa.",
    metricsFocus: ["Azure revenue growth", "Commercial bookings", "Operating margin", "Capex intensity", "Free cash flow"],
    sourceType: "curated_static",
    updatedAt: CURATED_UPDATED_AT,
  },
  NVDA: {
    companyName: "NVIDIA Corporation",
    sector: "Tecnologia",
    industry: "Semiconductors / accelerated computing",
    country: "Estados Unidos",
    exchange: "NASDAQ",
    currency: "USD",
    description: "NVIDIA desarrolla GPUs, sistemas acelerados, networking y software usados en inteligencia artificial, data centers, gaming, visualizacion profesional, automocion y edge computing.",
    businessSummary: "El caso esta dominado por Data Center: aceleradores, sistemas completos, interconexion y ecosistema CUDA. Para analizarla bien hay que distinguir demanda estructural de IA, digestion de inventarios y capacidad de suministro.",
    investorFocus: "Los inversores monitorean capex de hyperscalers, transicion de arquitecturas, gross margin, visibilidad de backlog, networking y riesgo de concentracion de clientes.",
    keyRisks: "Ciclicidad de semiconductores, restricciones de exportacion, concentracion de clientes, competencia ASIC/GPU y normalizacion del gasto en infraestructura de IA.",
    mainSegments: ["Data Center", "Gaming", "Professional Visualization", "Automotive", "OEM/Other"],
    keyDrivers: ["AI accelerator demand", "Hyperscaler capex", "Networking attach", "Supply availability", "Software ecosystem"],
    riskSensitivities: ["Export controls", "Customer concentration", "Inventory digestion", "Foundry capacity", "Competitive silicon"],
    whyInvestorsTrack: "Es el proxy publico mas directo para infraestructura de IA acelerada y gasto de hyperscalers.",
    metricsFocus: ["Data Center revenue", "Gross margin", "Inventory", "Customer concentration", "Capex signals"],
    sourceType: "curated_static",
    updatedAt: CURATED_UPDATED_AT,
  },
  GOOGL: {
    companyName: "Alphabet Inc.",
    sector: "Comunicacion",
    industry: "Internet advertising / cloud",
    country: "Estados Unidos",
    exchange: "NASDAQ",
    currency: "USD",
    description: "Alphabet opera Google Search, YouTube, Android, Google Cloud y negocios emergentes, con monetizacion principalmente publicitaria y una pata cloud de crecimiento.",
    businessSummary: "La lectura inversora separa Google Services, Google Cloud y Other Bets. Search sigue siendo el activo central, mientras Cloud e IA determinan el debate de crecimiento y capex.",
    investorFocus: "El mercado sigue monetizacion de busqueda, YouTube, Cloud, integracion de IA, traffic acquisition costs y exposicion regulatoria.",
    keyRisks: "Antitrust, privacidad, cambios de comportamiento por IA generativa, presion en TAC, competencia cloud y altos costos de infraestructura.",
    mainSegments: ["Google Search and ads", "YouTube", "Google Cloud", "Other Bets"],
    keyDrivers: ["Search ads", "YouTube monetization", "Cloud growth", "AI product integration", "Traffic acquisition costs"],
    riskSensitivities: ["Antitrust remedies", "AI search disruption", "Ad cycle", "Privacy regulation", "Cloud competition"],
    whyInvestorsTrack: "Es la referencia global de busqueda, publicidad digital e IA aplicada a plataformas de consumo.",
    metricsFocus: ["Search revenue", "YouTube ads", "Google Cloud margin", "TAC ratio", "Capex"],
    sourceType: "curated_static",
    updatedAt: CURATED_UPDATED_AT,
  },
  AMZN: {
    companyName: "Amazon.com, Inc.",
    sector: "Consumo",
    industry: "E-commerce / cloud / advertising",
    country: "Estados Unidos",
    exchange: "NASDAQ",
    currency: "USD",
    description: "Amazon combina marketplace, retail propio, Prime, logistica, publicidad digital, dispositivos y AWS, su plataforma de infraestructura cloud.",
    businessSummary: "El analisis separa AWS, retail norteamericano, internacional, publicidad y fulfillment. La mejora de margen suele depender de densidad logistica, ads, mix de terceros y disciplina de capex.",
    investorFocus: "Los inversores siguen crecimiento de AWS, margen retail, publicidad, Prime, capex logistico/cloud y conversion de flujo de caja.",
    keyRisks: "Competencia cloud y e-commerce, presion laboral/logistica, regulacion de marketplace, sensibilidad del consumidor y ciclos de inversion elevados.",
    mainSegments: ["North America", "International", "AWS", "Advertising", "Subscription services"],
    keyDrivers: ["AWS demand", "Retail operating margin", "Advertising growth", "Fulfillment efficiency", "Prime ecosystem"],
    riskSensitivities: ["Cloud competition", "Labor costs", "Regulatory scrutiny", "Consumer cycle", "Capex intensity"],
    whyInvestorsTrack: "Es una combinacion unica de escala en comercio, cloud y publicidad con multiples palancas de margen.",
    metricsFocus: ["AWS revenue and margin", "Retail operating income", "Advertising revenue", "Free cash flow", "Capex"],
    sourceType: "curated_static",
    updatedAt: CURATED_UPDATED_AT,
  },
  META: {
    companyName: "Meta Platforms, Inc.",
    sector: "Comunicacion",
    industry: "Social platforms / digital advertising",
    country: "Estados Unidos",
    exchange: "NASDAQ",
    currency: "USD",
    description: "Meta opera Facebook, Instagram, WhatsApp, Messenger y Reality Labs, monetizando audiencias globales principalmente a traves de publicidad digital.",
    businessSummary: "El negocio central es Family of Apps, impulsado por engagement, herramientas de anunciantes, recomendacion algoritimica e IA. Reality Labs representa una apuesta de largo plazo con alto consumo de capital.",
    investorFocus: "El seguimiento se enfoca en impresiones, pricing publicitario, Reels, mensajeria, eficiencia de gasto, capex de IA y perdidas de Reality Labs.",
    keyRisks: "Regulacion de privacidad, dependencia de publicidad, competencia por atencion, moderacion de contenidos y retorno incierto de inversiones en metaverso/IA.",
    mainSegments: ["Facebook", "Instagram", "WhatsApp/Messenger", "Reality Labs"],
    keyDrivers: ["Ad impressions", "Ad pricing", "Reels monetization", "AI ranking", "Expense discipline"],
    riskSensitivities: ["Privacy rules", "Ad cycle", "Reality Labs losses", "Capex growth", "Platform competition"],
    whyInvestorsTrack: "Es una de las plataformas publicitarias mas rentables y una lectura directa de IA aplicada a engagement y targeting.",
    metricsFocus: ["Ad revenue", "DAU/MAU", "Operating margin", "Reality Labs losses", "Capex"],
    sourceType: "curated_static",
    updatedAt: CURATED_UPDATED_AT,
  },
  TSLA: {
    companyName: "Tesla, Inc.",
    sector: "Consumo",
    industry: "Electric vehicles / energy storage",
    country: "Estados Unidos",
    exchange: "NASDAQ",
    currency: "USD",
    description: "Tesla fabrica vehiculos electricos, sistemas de almacenamiento de energia, baterias, software de conduccion asistida y servicios asociados.",
    businessSummary: "La tesis mezcla negocio automotriz, energia, software/autonomia y opcionalidad industrial. Para analizarla correctamente hay que separar volumen, precios, margen automotriz y contribucion de Energy.",
    investorFocus: "El mercado sigue entregas, ASPs, margen automotriz, costos de baterias, escala de energy storage, FSD/autonomia y nuevos modelos.",
    keyRisks: "Competencia EV, presion de precios, ejecucion industrial, regulacion de autonomia, concentracion de liderazgo y volatilidad de demanda.",
    mainSegments: ["Automotive", "Energy Generation and Storage", "Services and Other", "Software/autonomy"],
    keyDrivers: ["Deliveries", "Automotive gross margin", "Battery cost curve", "Energy storage deployments", "Software/autonomy monetization"],
    riskSensitivities: ["EV pricing", "Competitive launches", "Regulatory approvals", "Execution risk", "Consumer financing conditions"],
    whyInvestorsTrack: "Es el activo publico mas observado para EVs, electrificacion, baterias y opcionalidad de software/autonomia.",
    metricsFocus: ["Deliveries", "Automotive margin", "Energy revenue", "Operating cash flow", "Capex"],
    sourceType: "curated_static",
    updatedAt: CURATED_UPDATED_AT,
  },
  MELI: {
    companyName: "MercadoLibre, Inc.",
    sector: "Consumo",
    industry: "Latin American e-commerce / fintech",
    country: "Argentina",
    exchange: "NASDAQ",
    currency: "USD",
    description: "MercadoLibre opera un ecosistema latinoamericano de comercio electronico, pagos, credito, logistica, publicidad y servicios financieros digitales.",
    businessSummary: "La lectura correcta separa marketplace, Mercado Pago, credito, fulfillment y ads por geografia. Brasil, Mexico y Argentina tienen perfiles de crecimiento, margen y riesgo macro diferentes.",
    investorFocus: "Los inversores siguen GMV, TPV, take rate, riesgo crediticio, crecimiento en Brasil/Mexico, monetizacion de ads y apalancamiento operativo.",
    keyRisks: "Volatilidad macro latinoamericana, riesgo cambiario, competencia local/global, regulacion financiera y perdidas crediticias en ciclos adversos.",
    mainSegments: ["Marketplace", "Mercado Pago", "Mercado Credito", "Logistics/Fulfillment", "Advertising"],
    keyDrivers: ["GMV", "TPV", "Take rate", "Credit quality", "Brazil and Mexico scale"],
    riskSensitivities: ["FX and inflation", "Credit losses", "Regulation", "Competition", "Consumer cycle"],
    whyInvestorsTrack: "Es el proxy regional mas profundo para digitalizacion de comercio y fintech en America Latina.",
    metricsFocus: ["GMV", "TPV", "Fintech revenue", "Credit NPLs", "Operating margin"],
    sourceType: "curated_static",
    updatedAt: CURATED_UPDATED_AT,
  },
  YPF: {
    companyName: "YPF S.A.",
    sector: "Energia",
    industry: "Integrated oil & gas",
    country: "Argentina",
    exchange: "NYSE / BYMA",
    currency: "USD",
    description: "YPF es una compania energetica integrada argentina con exploracion, produccion, refinacion, comercializacion de combustibles y desarrollo de activos no convencionales en Vaca Muerta.",
    businessSummary: "El caso combina upstream shale, downstream regulado, precios locales de combustibles, estructura de deuda, capex y riesgo argentino. Vaca Muerta es la variable estrategica central.",
    investorFocus: "El mercado sigue produccion de shale oil/gas, realizacion de precios, capex, flujo de caja, deuda, regulacion local y politica energetica.",
    keyRisks: "Riesgo regulatorio argentino, controles de precios, restricciones cambiarias, necesidades de inversion, deuda y exposicion a precios internacionales de energia.",
    mainSegments: ["Upstream", "Downstream", "Gas and Power", "Vaca Muerta development"],
    keyDrivers: ["Shale production", "Realized fuel prices", "Refining margins", "Capex execution", "Argentina policy framework"],
    riskSensitivities: ["Local regulation", "FX controls", "Oil prices", "Country risk", "Funding access"],
    whyInvestorsTrack: "Es el principal vehiculo publico para exposicion a Vaca Muerta y normalizacion energetica argentina.",
    metricsFocus: ["Production growth", "Realized prices", "EBITDA", "Net debt", "Free cash flow"],
    sourceType: "curated_static",
    updatedAt: CURATED_UPDATED_AT,
  },
  YPFD: {
    companyName: "YPF S.A.",
    sector: "Energia",
    industry: "Integrated oil & gas",
    country: "Argentina",
    exchange: "BYMA",
    currency: "ARS",
    description: "YPFD representa la accion local de YPF en BYMA. El analisis fundamental se referencia a la misma compania y, cuando corresponde, a su ADR para datos internacionales.",
    businessSummary: "El caso combina upstream shale, downstream regulado, precios locales de combustibles, estructura de deuda, capex y riesgo argentino. Vaca Muerta es la variable estrategica central.",
    investorFocus: "El mercado sigue produccion de shale oil/gas, realizacion de precios, capex, flujo de caja, deuda, regulacion local y politica energetica.",
    keyRisks: "Riesgo regulatorio argentino, controles de precios, restricciones cambiarias, necesidades de inversion, deuda y exposicion a precios internacionales de energia.",
    mainSegments: ["Upstream", "Downstream", "Gas and Power", "Vaca Muerta development"],
    keyDrivers: ["Shale production", "Realized fuel prices", "Refining margins", "Capex execution", "Argentina policy framework"],
    riskSensitivities: ["Local regulation", "FX controls", "Oil prices", "Country risk", "Funding access"],
    whyInvestorsTrack: "Es la puerta local a YPF y a la tesis de desarrollo de Vaca Muerta desde BYMA.",
    metricsFocus: ["Production growth", "Realized prices", "EBITDA", "Net debt", "Free cash flow"],
    sourceType: "curated_static",
    updatedAt: CURATED_UPDATED_AT,
  },
  SPCX: {
    companyName: "SpaceX",
    sector: "Aeroespacial",
    industry: "Private space technology",
    country: "Estados Unidos",
    exchange: null,
    currency: "USD",
    description: "SpaceX es una compania privada de tecnologia espacial. En The Big Long, SPCX se clasifica como exposicion privada/especial, no como accion publica listada.",
    businessSummary: "La compania desarrolla lanzadores reutilizables, servicios de lanzamiento, Starlink, satelites y sistemas espaciales. No publica estados financieros completos ni cotiza continuamente como una compania listada.",
    investorFocus: "El interes inversor suele concentrarse en cadencia de lanzamientos, Starlink, contratos gubernamentales, reutilizacion, capex y rondas privadas de valuacion.",
    keyRisks: "No hay cotizacion publica continua, la informacion financiera es limitada, la liquidez depende de mercados privados y las valuaciones cambian por rondas discretas.",
    mainSegments: ["Launch services", "Starlink", "Spacecraft and systems", "Government/defense programs"],
    keyDrivers: ["Launch cadence", "Starlink subscriber economics", "Reusable rocket economics", "Government contracts", "Private financing rounds"],
    riskSensitivities: ["Private-market liquidity", "Limited disclosure", "Execution risk", "Regulatory approvals", "Capital intensity"],
    whyInvestorsTrack: "Es una exposicion privada seguida por su rol en lanzamiento orbital, conectividad satelital y contratos espaciales.",
    metricsFocus: ["Launch cadence", "Starlink operating indicators", "Private valuation rounds", "Capital needs", "Disclosure quality"],
    sourceType: "curated_static",
    updatedAt: CURATED_UPDATED_AT,
  },
};
